Parameters:
  VPCID:
    Type: String
    Description: Shared Infrastructure VPC to use
  PUBLICRT:
    Type: String
    Description: Shared Infrastructure Public Route Table
  PRIVATERTA:
    Type: String
    Description: Shared Infrastructure Private Route Table - A
  PRIVATERTB:
    Type: String
    Description: Shared Infrastructure Private Route Table - B
  APPVERSION:
    Type: String
    Description: Application Version to Deploy
  ENVIRONMENT:
    Type: String
    Description: Type of environment to provision
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - PROD
      - PRESALES
  APPPublicCIDRA:
    Type: String
    Description: CIDR to use for public subnet A for app environment.
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
  APPPublicCIDRB:
    Type: String
    Description: CIDR to use for public subnet B for app environment.
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
  APPPrivateCIDRA:
    Type: String
    Description: CIDR to use for private subnet A for app environment.
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
  APPPrivateCIDRB:
    Type: String
    Description: CIDR to use for private subnet B for app environment.
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/22
Mappings:
  RegionMap:
    us-east-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    us-east-2:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    us-west-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    us-west-2:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    sa-east-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    ca-central-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    eu-west-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    eu-west-2:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    eu-west-3:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    eu-central-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    ap-southeast-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    ap-southeast-2:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    ap-northeast-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    ap-northeast-2:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    ap-south-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
    cn-north-1:
      AMIFORLINUX: ami-0000000000000000 #Replace 0000000000000000 with the correct ami string for the region
  InstanceSize:
    DEV:
      "EC2" : "t2.micro"
    TEST:
      "EC2" : "t2.micro"
    PROD:
      "EC2" : "t2.small"
    PRESALES:
      "EC2" : "t2.micro"
Resources:
  SubnetPublicA: # Public Subnet for App Env in AZ - A
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref APPPublicCIDRA
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPCID
  SubnetPrivateA: # Private Subnet for App Env in AZ - A
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref APPPrivateCIDRA
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPCID
  SubnetPublicB: # Public Subnet for App Env in AZ - B  (not used yet)
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Ref APPPublicCIDRB
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPCID
  SubnetPrivateB: # Private Subnet for App Env in AZ - B (not used yet)
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Ref APPPrivateCIDRB
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPCID
  SubnetRouteTableAssociatePublicA: # Associates the subnet with a route table - passed via parameter
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PUBLICRT
      SubnetId: !Ref SubnetPublicA
  SubnetRouteTableAssociatePublicB: # Associates the subnet with a route table - passed via parameter
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PUBLICRT
      SubnetId: !Ref SubnetPublicB # Associates the subnet with a route table - passed via parameter
  SubnetRouteTableAssociatePrivateA: # Associates the subnet with a route table - passed via parameter
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PRIVATERTA
      SubnetId: !Ref SubnetPrivateA # Associates the subnet with a route table - passed via parameter
  SubnetRouteTableAssociatePrivateB: # Associates the subnet with a route table - passed via parameter
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PRIVATERTB
      SubnetId: !Ref SubnetPrivateB # Associates the subnet with a route table - passed via parameter
  ELB:
    Type: "AWS::ElasticLoadBalancing::LoadBalancer"
    Properties:
      CrossZone: true
      Instances:
        - !Ref EC2
      Listeners:
        -
          InstancePort: "80"
          InstanceProtocol: HTTP
          LoadBalancerPort: "80"
          Protocol: HTTP
      Subnets:
        - !Ref SubnetPublicA
        - !Ref SubnetPublicB
      SecurityGroups:
        - !Ref SG
  SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Join ["", ["Stack ", !Ref "AWS::StackId", " Application V", !Ref APPVERSION, " - ", !Ref ENVIRONMENT]]
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        -
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          ToPort: "80"
          FromPort: "80"
        -
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          ToPort: "22"
          FromPort: "22"
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          ToPort: "-1"
          IpProtocol: "-1"

  EC2: # for now this is in a public subnet, needs to be changed.
    Type: "AWS::EC2::Instance"
    DeletionPolicy: Delete
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMIFORLINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref ENVIRONMENT, EC2]
      KeyName: AdvancedCFN
      SecurityGroupIds:
        - !Ref SG
      SubnetId: !Ref SubnetPublicA
      UserData:
        UserData: 
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
Outputs:
  Endpoint:
    Description: Application Address
    Value: !Join ["", ["http://", !GetAtt ELB.DNSName, "/app.php"]]
