AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 - RDS - S3'
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      DBName: YourDataBaseName
      Engine: MySQL
      MasterUsername: YourUserName
      MasterUserPassword: YourPassword
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0915e09cc7ceee3ab # Amazon Linux AMI 2018.03.0 (HVM), SSD Volume Type , N.Virginia
      InstanceType: t2.micro
  S3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: YourBucketName # replace YourBucketName with random or remove the BucketName

